// <auto-generated />
namespace RESTful_API_OAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitRESTful_API_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitRESTful_API_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "201708020429304_InitRESTful_API_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
